### ISSUE TITLE
etcd-operator deploy fails: is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default"

### ISSUE THREAD

**Issue by nnachefski** [coreos/vault-operator#340]
level=fatal msg="create service failed: pods "etcd-operator-764f7ff957-4h5bw" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default": User "system:serviceaccount:default:default" cannot get pods in project "default"

On Openshift 3.10/kube 1.10

**Comment by aweiteka** [comment]
You'll either need to grant the default serviceaccount permissions or specify a service account in the deployment, e.g.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd-operator
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      serviceAccount: etcd-operator
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.1
        command:
        - etcd-operator
        - "--create-crd=false"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

However, given #332 I would recommend https://github.com/banzaicloud/bank-vaults
