### ISSUE TITLE
Ingress to access Vault

### ISSUE THREAD

**Issue by s4rd1nh4** [coreos/vault-operator#341]
I have been deployed the vault example, but dont can configure ingress to access externally

Vault
```
apiVersion: "vault.security.coreos.com/v1alpha1"
kind: "VaultService"
metadata:
  name: "example"
spec:
  nodes: 1
  version: "0.10.4"
```
Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  generation: 6
  labels:
    app: vault
  name: kube-vault
  namespace: vault-production
spec:
  rules:
  - host: secret.devops.agilitynetworks.com.br
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: 8200
        path: /
  tls:
  - hosts:
    - secret.devops.agilitynetworks.com.br
    secretName: tls-secret-wildcard
```

Secret
```
kubectl get secret tls-secret-wildcard 
NAME                  TYPE                DATA      AGE
tls-secret-wildcard   kubernetes.io/tls   2         5d

```
